[package]
name = "cmago"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "cmago"
path = "./cmago.rs"

[dependencies]
toml = "0.9.5"
serde = { version = "1.0.219", features = ["derive"] }
colored = "3.0.0"
argparse = "0.2.2"
url = "2.2"